
using System;
using System.Collections.Generic;

namespace OptimizeDelete.UtilsObjects
{
	
	public class Deletes
	{
		public List<Querys> listQuery;
		public string sqlDeletes(Querys query)
		{
			var tab = Tabelas.Instancia;			
			listQuery = new List<Querys>();
			string filiais =" in ("+tab.filialMarcada.Remove(tab.filialMarcada.Length -1 , 1) +")";
			 
			
			listQuery.Add(new Querys(query.tabela="movment" ,query.query="DELETE movment from movment INNER JOIN produto ON (produto.produto_id=movment.produto_id) INNER JOIN grupo ON (grupo.grupo_id=produto.grupo_id) where movment.data_hora between '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and movment.filial_id "+filiais+" and ((movment.entrega = 'N') or (movment.entrega = 'S' and movment.dtchegada_entrega between '"+tab.dtInicial+"' and '" +tab.dtFinal+ "')) and grupo.controlado = 'N';"));
			listQuery.Add(new Querys(query.tabela="lote_saida", query.query="Delete lote_saida from lote_saida left join movment on (movment.filial_id = lote_saida.filial_id) and (movment.numlanc = lote_saida.numlanc) and (movment.produto_id = lote_saida.produto_id) where movment.movment_id is NULL and movment.data_hora between '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and movment.filial_id  "+filiais+" ; "));
			listQuery.Add(new Querys(query.tabela="orcament" , query.query= "Delete orcament  from orcament where orcament.data between  '" + tab.dtInicial+"' and '" +tab.dtFinal+ "' and Status = 'F' and orcament.filial_id  "+filiais+"  ;"));
			listQuery.Add(new Querys(query.tabela="logs",query.query="Delete logs from logs where logs.data_hora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and filial_fisica_id  "+filiais+" ;" ));
			listQuery.Add(new Querys(query.tabela="alt_linear" ,query.query="Delete from alt_linear where alt_linear.data between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "'  and alt_linear.filial_id  "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela="itens_alt_linear" ,query.query="Delete itens_alt_linear from itens_alt_linear left join alt_linear on (itens_alt_linear.filial_id = alt_linear.filial_id) and (itens_alt_linear.alt_linear_id = alt_linear.alt_linear_id) where alt_linear.alt_linear_id is NULL and alt_linear.data between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "'  and alt_linear.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="pagar" ,query.query="Delete from pagar where pagar.dt_emissao between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and pagar.filial_id  "+filiais+"  and valor_pago > 0;"));
			listQuery.Add(new Querys(query.tabela="pagamentos" ,query.query="Delete from pagamentos where datahora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and filial_id  "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela="pedidos" ,query.query="Delete from pedidos where pedidos.datahora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and pedidos.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="pedeletronico" ,query.query="Delete from pedeletronico where pedeletronico.datahora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and pedeletronico.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="pedeletronico_arquivos" ,query.query="Delete pedeletronico_arquivos from pedeletronico_arquivos left join pedeletronico on (pedeletronico_arquivos.filfisica_id = pedeletronico.filfisica_id)and (pedeletronico_arquivos.fornece_id = pedeletronico.fornece_id)and (pedeletronico_arquivos.numlanc = pedeletronico.numlanc) where pedeletronico.pedeletronico_id is NULL and  pedeletronico.datahora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and pedeletronico.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="preco_medio_custo_historico" ,query.query="Delete from preco_medio_custo_historico where preco_medio_custo_historico.datahora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and   preco_medio_custo_historico.filial_id  "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela="remanejamento" ,query.query="Delete from remanejamento where remanejamento.data_hora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and recebido = 'S';"));
			listQuery.Add(new Querys(query.tabela="relbomdia" ,query.query="Delete from relbomdia where relbomdia.data_hora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and relbomdia.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="faltas" ,query.query="Delete from faltas where faltas.data  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and faltas.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="entradas" ,query.query="Delete entradas from entradas INNER JOIN produto ON (produto.produto_id=entradas.produto_id) INNER JOIN grupo ON (grupo.grupo_id=produto.grupo_id) where entradas.data_hora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and entradas.operacao in(2,3) and grupo.controlado = 'N' and entradas.dafilial_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela="entradas_lote" ,query.query="Delete entradas_lote from entradas_lote left join entradas on (entradas_lote.filfisica_id = entradas.filial_id) and (entradas_lote.entradas_id = entradas.entradas_id) where entradas.entradas_id is NULL and entradas.data_hora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "'  and entradas.dafilial_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela="entradas_lote_temp" ,query.query="Delete entradas_lote_temp from entradas_lote_temp left join entradas on (entradas_lote_temp.filfisica_id = entradas.filial_id) and (entradas_lote_temp.entradas_id = entradas.entradas_id) where entradas.entradas_id is NULL and entradas.data_hora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and entradas.dafilial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="estoque_posterior" ,query.query="Delete from estoque_posterior where estoque_posterior.data_hora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and estoque_posterior.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="cheques" ,query.query="Delete from cheques where cheques.data between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and cheques.filial_id  "+filiais+" and baixado = 'S';"));
			listQuery.Add(new Querys(query.tabela="transferencia" ,query.query="Delete transferencia from transferencia INNER JOIN produto ON (produto.produto_id=transferencia.produto_id) INNER JOIN grupo ON (grupo.grupo_id=produto.grupo_id) where transferencia.data_hora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and transferencia.ok = 'S' and grupo.controlado = 'N';"));
			listQuery.Add(new Querys(query.tabela="receber",query.query="Delete from receber where receber.datahora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and receber.amort >= 100 and receber.filial_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela="baixa_adm_det_rec" ,query.query="Delete baixa_adm_det_rec from baixa_adm_det_rec left join receber on (baixa_adm_det_rec.filial_id = receber.filial_id) and (baixa_adm_det_rec.receber_id = receber.receber_id) where receber.receber_id is NULL and receber.datahora  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "'  and receber.filial_id "+filiais+" ; "));
			listQuery.Add(new Querys(query.tabela="baixa_adm" ,query.query="Delete baixa_adm from baixa_adm left join baixa_adm_det_rec on (baixa_adm_det_rec.baixa_adm_id = baixa_adm.baixa_adm_id) where baixa_adm_det_rec.baixa_adm_det_rec_id is NULL and baixa_adm.datahora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and baixa_adm.filial_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="baixa_adm_det" ,query.query="Delete baixa_adm_det from baixa_adm_det left join baixa_adm on (baixa_adm_det.baixa_adm_id = baixa_adm.baixa_adm_id) where baixa_adm.baixa_adm_id is NULL and baixa_adm.datahora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and baixa_adm.filial_id "+filiais+" ; "));
			listQuery.Add(new Querys(query.tabela="mensagens" ,query.query="Delete from mensagens where mensagens.apagado = 'S' or mensagens.datahora between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "'and mensagens.filial_id "+filiais+"  ;"));
			listQuery.Add(new Querys(query.tabela="nfe_det" ,query.query="DELETE nfe_det from nfe_det a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) and b.dtemissao  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="nfe_duplicata" ,query.query="DELETE nfe_duplicata from nfe_duplicata a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) and b.dtemissao  between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="nfe_pagamento_cab" ,query.query="DELETE nfe_pagamento_cab from nfe_pagamento_cab a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) where b.dtemissao between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="nfe_lote",query.query="DELETE nfe_lote from nfe_lote a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) where b.dtemissao between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="nfe_pagamento" ,query.query="DELETE nfe_pagamento from nfe_pagamento a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) where b.dtemissao between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+ ";"));
			listQuery.Add(new Querys(query.tabela="nfe_cab_xml" ,query.query="DELETE nfe_cab_xml FROM nfe_cab_xml a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) where b.dtemissao between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela="nfe_cab" ,query.query="DELETE nfe_cab FROM nfe_cab a JOIN nfe_cab b ON (a.filfisica_id = b.filfisica_id AND a.nfe_cab_id = b.nfe_cab_id) where b.dtemissao between  '"+tab.dtInicial+"' and '" +tab.dtFinal+ "' and b.filfisica_id "+filiais+";"));
			listQuery.Add(new Querys(query.tabela = "acertaestrutura_log", query.query = "DELETE acertaestrutura_log FROM acertaestrutura_log WHERE datahorainicio BETWEEN '"+tab.dtInicial +"' AND '"+ tab.dtFinal+"' AND filial_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela = "acode_arquivos", query.query = "DELETE acode_arquivos FROM acode_arquivos where acode_arquivos.data_geracao between '"+tab.dtInicial + "' and '"+tab.dtFinal+"' and acode_arquivos.filial_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela = "acode_config", query.query = "DELETE acode_config FROM acode_config WHERE acode_config.data_alteracao BETWEEN '"+tab.dtInicial+"' AND '"+tab.dtFinal+"' AND acode_config.filial_id"+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela = "acode_config_filial", query.query = "DELETE acode_config_filial FROM acode_config_filial WHERE acode_config_filial.data_alteracao BETWEEN '"+tab.dtInicial+"' and '"+tab.dtFinal+"'AND acode_config_filial.filial_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela = "ajuste_bc_pis_cofins", query.query = "DELETE ajuste_bc_pis_cofins FROM ajuste_bc_pis_cofins WHERE ajuste_bc_pis_cofins.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND ajuste_bc_pis_cofins.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "ajuste_bc_pis_cofins_item", query.query = "DELETE ajuste_bc_pis_cofins_item FROM ajuste_bc_pis_cofins_item WHERE ajuste_bc_pis_cofins_item.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND ajuste_bc_pis_cofins_item.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "ajuste_bc_pis_cofins_det", query.query = "DELETE ajuste_bc_pis_cofins_det FROM ajuste_bc_pis_cofins_det JOIN ajuste_bc_pis_cofins_item ON(ajuste_bc_pis_cofins_det.ajuste_bc_pis_cofins_item_id = ajuste_bc_pis_cofins_item.ajuste_bc_pis_cofins_item_id) WHERE ajuste_bc_pis_cofins_det.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND ajuste_bc_pis_cofins_item.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "ajuste_contrib_cofins", query.query = "DELETE ajuste_contrib_cofins FROM  ajuste_contrib_cofins left join nota_fiscal  ON ( ajuste_contrib_cofins.nota_fiscal_id = nota_fiscal.nota_fiscal_id) WHERE  ajuste_contrib_cofins.`data` between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND nota_fiscal.filial_id   " + filiais + " or nota_fiscal.nota_fiscal_id IS null;"));
			listQuery.Add(new Querys(query.tabela = "ajuste_contrib_pis", query.query = "DELETE ajuste_contrib_pis FROM  ajuste_contrib_pis left join nota_fiscal  ON ( ajuste_contrib_pis.nota_fiscal_id = nota_fiscal.nota_fiscal_id) WHERE  ajuste_contrib_pis.data between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND nota_fiscal.filial_id  " + filiais + " OR nota_fiscal.nota_fiscal_id IS null ;"));
			listQuery.Add(new Querys(query.tabela = "altpreco_agend_cabec", query.query = "DELETE altpreco_agend_cabec FROM altpreco_agend_cabec WHERE altpreco_agend_cabec.data_cadastro_altpreco between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND altpreco_agend_cabec.filial_lancamento_id "+filiais+" ;"));
			listQuery.Add(new Querys(query.tabela = "altpreco_agend_precos", query.query = "DELETE altpreco_agend_precos FROM altpreco_agend_precos WHERE altpreco_agend_precos.data_execucao_altpreco BETWEEN  '" + tab.dtInicial + "' and '" + tab.dtFinal + "' and altpreco_agend_precos.filial_lancamento_id " + filiais + "; "));
			listQuery.Add(new Querys(query.tabela = "apur_icms_item", query.query = "DELETE apur_icms_item FROM apur_icms_item LEFT  JOIN  nota_fiscal ON (apur_icms_item.nota_fiscal_id  = nota_fiscal.nota_fiscal_id AND apur_icms_item.filial_id = nota_fiscal.filial_id) WHERE nota_fiscal.data_emissao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND apur_icms_item.filial_id "+ filiais + " OR nota_fiscal.nota_fiscal_id IS null and apur_icms_item.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "arqs_efd", query.query = "DELETE arqs_efd  from arqs_efd WHERE  arqs_efd.dtcadastro BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND arqs_efd.dafilial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "arqs_sngpc", query.query = "DELETE arqs_sngpc FROM arqs_sngpc WHERE arqs_sngpc.data_geracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND arqs_sngpc.filial_id " + filiais + " ; "));
			listQuery.Add(new Querys(query.tabela = "arq_inv_sngc_hist_cabec", query.query = "DELETE arq_inv_sngc_hist_cabec FROM arq_inv_sngc_hist_cabec WHERE arq_inv_sngc_hist_cabec.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND arq_inv_sngc_hist_cabec.filial_id "+filiais+" ; "));
			listQuery.Add(new Querys(query.tabela = "arq_inv_sngc_hist_lote", query.query = "DELETE arq_inv_sngc_hist_lote FROM arq_inv_sngc_hist_lote LEFT JOIN arq_inv_sngc_hist_cabec ON (arq_inv_sngc_hist_lote.arq_inv_sngc_hist_cabec_id = arq_inv_sngc_hist_cabec.arq_inv_sngc_hist_cabec_id) WHERE arq_inv_sngc_hist_cabec.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND arq_inv_sngc_hist_lote.fillogica_id   OR arq_inv_sngc_hist_cabec.arq_inv_sngc_hist_cabec_id IS NULL;"));
			listQuery.Add(new Querys(query.tabela = "arq_inv_sngc_hist_prod", query.query = "DELETE arq_inv_sngc_hist_prod FROM arq_inv_sngc_hist_prod left JOIN arq_inv_sngc_hist_cabec ON(arq_inv_sngc_hist_prod.arq_inv_sngc_hist_cabec_id = arq_inv_sngc_hist_cabec.arq_inv_sngc_hist_cabec_id) WHERE   arq_inv_sngc_hist_cabec.arq_inv_sngc_hist_cabec_id IS  NULL OR arq_inv_sngc_hist_cabec.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND arq_inv_sngc_hist_cabec.filial_id " + filiais + " ; "));
			listQuery.Add(new Querys(query.tabela = "ativador_log", query.query = "DELETE ativador_log FROM ativador_log WHERE ativador_log.data_inicio between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND ativador_log.filial_id " + filiais + " ; "));
			listQuery.Add(new Querys(query.tabela = "atualizacao_precos", query.query = "DELETE atualizacao_precos FROM atualizacao_precos WHERE atualizacao_precos.dt_atualizacao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' ;"));
			listQuery.Add(new Querys(query.tabela = "caixas", query.query = "DELETE caixas FROM caixas WHERE caixas.dtinicial between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND caixas.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "caixaconf", query.query = "DELETE caixaconf FROM caixaconf LEFT JOIN caixas on (caixaconf.caixas_id =  caixas.caixas_id AND caixaconf.filial_id =  caixas.filial_id) WHERE caixas.dtinicial BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND caixaconf.filial_id or caixas.caixas_id is null  AND caixaconf.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "cancelamento_movment", query.query = "DELETE cancelamento_movment FROM cancelamento_movment cm left JOIN movment mov ON(cm.filial_id = mov.filial_id and  cm.movment_id_canc = mov.movment_id) WHERE mov.data_hora  between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND mov.cancelado ='S' AND cm.filial_id " + filiais + " AND cm.filial_id_canc   " + filiais + " OR  mov.movment_id IS NULL ;"));
			listQuery.Add(new Querys(query.tabela = "cliente_tab_desconto", query.query = "DELETE cliente_tab_desconto  FROM cliente_tab_desconto left JOIN tabela_desconto ON (cliente_tab_desconto.tabela_desconto_id = tabela_desconto.tabela_desconto_id) WHERE tabela_desconto.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND cliente_tab_desconto.filial_id " + filiais + " or tabela_desconto.tabela_desconto_id is null and cliente_tab_desconto.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "codnofornec_log", query.query = "DELETE codnofornec_log FROM codnofornec_log WHERE codnofornec_log.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND codnofornec_log.filial_fisica_id ;"));
			listQuery.Add(new Querys(query.tabela = "comunicacao", query.query = "DELETE comunicacao FROM comunicacao WHERE comunicacao.filial_id  ;"));
			//listQuery.Add(new Querys(query.tabela = "comunicacao_entradas_log", query.query = "DELETE comunicacao_entradas_log FROM comunicacao_entradas_log WHERE comunicacao_entradas_log.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND comunicacao_entradas_log.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "comunicacao_transferencia_log", query.query = "DELETE comunicacao_transferencia_log FROM comunicacao_transferencia_log WHERE comunicacao_transferencia_log.data_hora  between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND comunicacao_transferencia_log.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao", query.query = "DELETE conciliacao FROM conciliacao WHERE conciliacao.dtcadastro   between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacaolanc", query.query = "DELETE conciliacaolanc FROM conciliacaolanc LEFT  join conciliacao ON (conciliacaolanc.conciliacao_id = conciliacao.conciliacao_id) where  conciliacaolanc.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao.filial_id " + filiais + " OR conciliacao.conciliacao_id IS NULL  and conciliacao.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_ajustes", query.query = "DELETE conciliacao_ajustes FROM conciliacao_ajustes WHERE conciliacao_ajustes.data_ajuste between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_ajustes.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_antecipacao_lote", query.query = "DELETE conciliacao_antecipacao_lote FROM conciliacao_antecipacao_lote WHERE conciliacao_antecipacao_lote.data_antecipacao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_antecipacao_lote.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_financeiro", query.query = "DELETE conciliacao_financeiro FROM conciliacao_financeiro WHERE conciliacao_financeiro.data_pagamento between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_financeiro.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_financeiro_log", query.query = "DELETE conciliacao_financeiro_log FROM conciliacao_financeiro_log WHERE conciliacao_financeiro_log.data_cadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_financeiro_log.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_informacao", query.query = "DELETE conciliacao_informacao FROM conciliacao_informacao LEFT  JOIN transacao_cart_pbm ON(conciliacao_informacao.transacao_cart_pbm_id = transacao_cart_pbm.transacao_cart_pbm_id) WHERE transacao_cart_pbm.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND transacao_cart_pbm.filial_id " + filiais + " OR transacao_cart_pbm.transacao_cart_pbm_id IS NULL  AND transacao_cart_pbm.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_lote_parc_paga", query.query = "DELETE conciliacao_lote_parc_paga FROM conciliacao_lote_parc_paga WHERE conciliacao_lote_parc_paga.data_pagamento between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_lote_parc_paga.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_lote_venda", query.query = "DELETE conciliacao_lote_venda FROM conciliacao_lote_venda WHERE conciliacao_lote_venda.data_lote between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_lote_venda.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_transacoes", query.query = "DELETE conciliacao_transacoes FROM conciliacao_transacoes WHERE conciliacao_transacoes.data_venda between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_transacoes.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliacao_trans_parcela", query.query = "DELETE conciliacao_trans_parcela FROM conciliacao_trans_parcela WHERE conciliacao_trans_parcela.data_previsao_pgto_rede between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliacao_trans_parcela.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliador_atividades", query.query = "DELETE conciliador_atividades FROM conciliador_atividades WHERE conciliador_atividades.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliador_atividades.filial_fisica_id  " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "conciliador_atividades_hist", query.query = "DELETE conciliador_atividades_hist  FROM conciliador_atividades_hist WHERE conciliador_atividades_hist.data_periodo_inicio between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliador_atividades_hist.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conciliador_atividades_log", query.query = "DELETE conciliador_atividades_log FROM conciliador_atividades_log left JOIN conciliador_atividades ON (conciliador_atividades_log.conciliador_atividades_id = conciliador_atividades.conciliador_atividades_id)  WHERE conciliador_atividades.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND  conciliador_atividades.filial_id " + filiais + " OR conciliador_atividades_log.conciliador_atividades_id IS NULL  AND  conciliador_atividades.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "conciliador_atividades_periodo", query.query = "DELETE conciliador_atividades_periodo FROM conciliador_atividades_periodo LEFT JOIN conciliador_atividades ON (conciliador_atividades_periodo.conciliador_atividades_id = conciliador_atividades.conciliador_atividades_id) WHERE conciliador_atividades.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conciliador_atividades.filial_id " + filiais + " OR conciliador_atividades.conciliador_atividades_id IS NULL  AND conciliador_atividades.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "conferencia_det", query.query = "DELETE conferencia_det FROM conferencia_det  LEFT JOIN nfe_cab ON (conferencia_det.nfe_cab_id =  nfe_cab.nfe_cab_id AND conferencia_det.filfisica_id = nfe_cab.fillogica_id) WHERE nfe_cab.dtemissao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND  nfe_cab.fillogica_id   " + filiais + " OR nfe_cab.nfe_cab_id IS NULL  AND  nfe_cab.fillogica_id   " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "conferencia_lote", query.query = "DELETE conferencia_lote FROM conferencia_lote LEFT JOIN nfe_cab ON (conferencia_lote.nfe_cab_id = nfe_cab.nfe_cab_id AND conferencia_lote.filfisica_id =  nfe_cab.fillogica_id) WHERE nfe_cab.dtemissao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND nfe_cab.fillogica_id   " + filiais + " OR nfe_cab.nfe_cab_id IS NULL  AND nfe_cab.fillogica_id   " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "config_comunicador", query.query = "DELETE config_comunicador FROM  config_comunicador WHERE config_comunicador.dt_ini_ultima_comunicacao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_comunicador.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_conferencia_caixa", query.query = "DELETE config_conferencia_caixa FROM config_conferencia_caixa WHERE config_conferencia_caixa.dtalteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_conferencia_caixa.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_conta_caixa", query.query = "DELETE config_conta_caixa FROM config_conta_caixa LEFT JOIN bancos_contas ON (config_conta_caixa.bancos_contas_id  = bancos_contas.bancos_contas_id AND config_conta_caixa.filial_id = bancos_contas.filial_id)  WHERE bancos_contas.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_conta_caixa.filial_id " + filiais + " or bancos_contas.bancos_contas_id is null and  config_conta_caixa.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_entradas", query.query = "DELETE config_entradas FROM  config_entradas WHERE config_entradas.dtalteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' and config_entradas.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_entregas", query.query = "DELETE config_entregas FROM config_entregas WHERE config_entregas.dtalteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' and config_entregas.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_geral", query.query = "DELETE config_geral FROM config_geral WHERE config_geral.dt_alteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND  config_geral.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_integracoes", query.query = "DELETE config_integracoes FROM config_integracoes WHERE config_integracoes.dtalteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_integracoes.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_lembreremedio", query.query = "DELETE config_lembreremedio FROM config_lembreremedio WHERE config_lembreremedio.dtalteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_lembreremedio.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_premiacao", query.query = "DELETE config_premiacao FROM config_premiacao WHERE config_premiacao.dtalteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_premiacao.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_receber", query.query = "DELETE config_receber FROM config_receber WHERE config_receber.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_retroativo_piscofins", query.query = "DELETE config_retroativo_piscofins FROM config_retroativo_piscofins WHERE config_retroativo_piscofins.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "config_sugcompra", query.query = "DELETE config_sugcompra FROM config_sugcompra WHERE config_sugcompra.dt_alteracao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND config_sugcompra.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "conf_caixa_loja", query.query = "DELETE conf_caixa_loja FROM  conf_caixa_loja WHERE conf_caixa_loja.dt_inicio_conf between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' and conf_caixa_loja.filfisica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "conf_caixa_loja_tipospgto", query.query = "DELETE conf_caixa_loja_tipospgto FROM conf_caixa_loja_tipospgto LEFT JOIN conf_caixa_loja ON (conf_caixa_loja_tipospgto.conf_caixa_loja_id = conf_caixa_loja.conf_caixa_loja_id and conf_caixa_loja.filfisica_id = conf_caixa_loja_tipospgto.filfisica_id) WHERE conf_caixa_loja.dt_inicio_conf between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND conf_caixa_loja_tipospgto.filfisica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "contingencia_nfe", query.query = "DELETE contingencia_nfe FROM contingencia_nfe WHERE contingencia_nfe.dt_cadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND contingencia_nfe.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "correlacao_csosn_default", query.query = "DELETE correlacao_csosn_default FROM  correlacao_csosn_default WHERE correlacao_csosn_default.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "correlacao_csosn_devolucao", query.query = "DELETE correlacao_csosn_devolucao FROM correlacao_csosn_devolucao WHERE correlacao_csosn_devolucao.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "correlacao_csosn_entrada", query.query = "DELETE correlacao_csosn_entrada FROM correlacao_csosn_entrada WHERE correlacao_csosn_entrada.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "cotacao", query.query = "DELETE cotacao FROM cotacao WHERE cotacao.validade  between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND cotacao.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "cotacao_online", query.query = "DELETE cotacao_online  FROM cotacao_online WHERE cotacao_online.validade between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND cotacao_online.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "cotafor", query.query = "DELETE cotafor FROM cotafor WHERE cotafor.validade between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND cotafor.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "credenc_cart", query.query = "DELETE credenc_cart FROM credenc_cart WHERE credenc_cart.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_cart.filfisica_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "credenc_cart_config", query.query = "DELETE credenc_cart_config FROM credenc_cart_config WHERE credenc_cart_config.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_cart_config.fillogica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credenc_cart_config_banco", query.query = "DELETE credenc_cart_config_banco FROM credenc_cart_config_banco WHERE credenc_cart_config_banco.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_cart_config_banco.filfisica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credenc_cart_config_bandeira", query.query = "DELETE credenc_cart_config_bandeira FROM credenc_cart_config_bandeira WHERE credenc_cart_config_bandeira.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_cart_config_bandeira.fillogica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credenc_cart_config_dia", query.query = "DELETE credenc_cart_config_dia FROM credenc_cart_config_dia WHERE credenc_cart_config_dia.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_cart_config_dia.filfisica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credenc_maquineta_terminal", query.query = "DELETE	credenc_maquineta_terminal from credenc_maquineta_terminal  WHERE credenc_maquineta_terminal.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND  credenc_maquineta_terminal.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_maquineta_terminal.fillogica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credenc_pbm", query.query = "DELETE credenc_pbm FROM  credenc_pbm WHERE credenc_pbm.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' and credenc_pbm.filfisica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credenc_pbm_config", query.query = "DELETE credenc_pbm_config FROM credenc_pbm_config WHERE credenc_pbm_config.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_pbm_config.fillogica_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "credenc_pbm_prod", query.query = "DELETE credenc_pbm_prod FROM  credenc_pbm_prod LEFT JOIN credenc_pbm_config ON (credenc_pbm_prod.credenc_pbm_config_id =  credenc_pbm_config.credenc_pbm_config_id) WHERE credenc_pbm_config.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credenc_pbm_config.fillogica_id   " + filiais + " OR credenc_pbm_config.credenc_pbm_config_id IS NULL AND credenc_pbm_config.fillogica_id   " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "credito_icms_st", query.query = "DELETE credito_icms_st FROM credito_icms_st WHERE credito_icms_st.data_arquivo between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credito_icms_st.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "credito_icms_st_item", query.query = "DELETE credito_icms_st_item FROM credito_icms_st_item WHERE credito_icms_st_item.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "credito_icms_st_parcela", query.query = "DELETE credito_icms_st_parcela FROM credito_icms_st_parcela WHERE credito_icms_st_parcela.data_parcela between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credito_icms_st_parcela.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "credito_recolhimento_fcp", query.query = "DELETE credito_recolhimento_fcp FROM credito_recolhimento_fcp WHERE credito_recolhimento_fcp.data_cadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND credito_recolhimento_fcp.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "ctrlpagtomin", query.query = "DELETE ctrlpagtomin FROM ctrlpagtomin WHERE ctrlpagtomin.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND ctrlpagtomin.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "cupons_canc_auto", query.query = "DELETE cupons_canc_auto FROM  cupons_canc_auto WHERE cupons_canc_auto.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND cupons_canc_auto.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "curvaabc", query.query = "DELETE curvaabc FROM curvaabc WHERE curvaabc.`data` between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND curvaabc.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "dados_hardware", query.query = "DELETE dados_hardware FROM dados_hardware WHERE dados_hardware.dt_ult_checagem between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND dados_hardware.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "dados_obrig_icms_st", query.query = "DELETE dados_obrig_icms_st FROM  dados_obrig_icms_st WHERE dados_obrig_icms_st.dt_alteracao  between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND dados_obrig_icms_st.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "dav", query.query = "DELETE dav FROM dav WHERE dav.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND dav.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "dav_item", query.query = "DELETE dav_item  FROM dav_item LEFT JOIN dav ON (dav_item.dav_id = dav.dav_id) WHERE dav.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND dav.filial_id " + filiais + " OR dav.dav_id IS NULL  AND dav.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "dav_movment", query.query = "DELETE dav_movment FROM dav_movment LEFT JOIN  dav ON (dav_movment.dav_id =  dav.dav_id AND dav_movment.filial_id = dav.filial_id) WHERE  dav.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND dav_movment.filial_id " + filiais + " OR dav.dav_id IS null  AND dav_movment.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "dav_numlanc", query.query = "DELETE dav_numlanc FROM dav_numlanc LEFT JOIN dav ON(dav_numlanc.num_dav = dav.num_dav AND dav_numlanc.filial_id = dav.filial_id) WHERE  dav.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND dav_numlanc.filial_id " + filiais + " OR dav.dav_id IS null  AND dav_numlanc.filial_id " + filiais + "; "));
			listQuery.Add(new Querys(query.tabela = "demais_docs", query.query = "DELETE demais_docs FROM demais_docs WHERE demais_docs.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' and  demais_docs.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "depositoschq", query.query = "DELETE depositoschq FROM depositoschq WHERE depositoschq.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND depositoschq.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "depreciacao_amortizacao", query.query = "DELETE depreciacao_amortizacao FROM  depreciacao_amortizacao WHERE depreciacao_amortizacao.dtcadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND depreciacao_amortizacao.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "desconto_quantidade", query.query = "DELETE desconto_quantidade FROM desconto_quantidade WHERE desconto_quantidade.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "devolucao_forn", query.query = "DELETE devolucao_forn FROM devolucao_forn WHERE devolucao_forn.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND devolucao_forn.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "devolucao_forn_lote", query.query = "DELETE devolucao_forn_lote FROM devolucao_forn_lote LEFT  JOIN devolucao_forn ON( devolucao_forn_lote.devolucao_forn_id = devolucao_forn.devolucao_forn_id AND devolucao_forn_lote.filial_id = devolucao_forn.filial_id) WHERE devolucao_forn.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND devolucao_forn_lote.filial_id " + filiais + " OR devolucao_forn.devolucao_forn_id IS NULL AND devolucao_forn_lote.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "diverg_conferencia_det", query.query = "DELETE diverg_conferencia_det FROM diverg_conferencia_det LEFT JOIN nfe_cab ON ( diverg_conferencia_det.nfe_cab_id = nfe_cab.nfe_cab_id AND diverg_conferencia_det.filfisica_id =  nfe_cab.fillogica_id) WHERE nfe_cab.dtemissao between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND diverg_conferencia_det.filfisica_id " + filiais + " OR nfe_cab.nfe_cab_id is null  AND diverg_conferencia_det.filfisica_id " + filiais +"; "));
			listQuery.Add(new Querys(query.tabela = "diverg_conferencia_lote", query.query = "DELETE diverg_conferencia_lote FROM diverg_conferencia_lote WHERE diverg_conferencia_lote.data_nfe between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND diverg_conferencia_lote.filfisica_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "doc_fiscal", query.query = "DELETE doc_fiscal FROM doc_fiscal WHERE doc_fiscal.data_hora_cadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND doc_fiscal.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "doc_fiscal_arquivo", query.query = "DELETE doc_fiscal_arquivo FROM doc_fiscal_arquivo left JOIN doc_fiscal ON(doc_fiscal_arquivo.doc_fiscal_id = doc_fiscal.doc_fiscal_id) WHERE doc_fiscal.data_hora_cadastro between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND doc_fiscal_arquivo.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "ecomm_alertas", query.query = "DELETE ecomm_alertas FROM ecomm_alertas WHERE ecomm_alertas.data_hora between '" + tab.dtInicial + "' and '" + tab.dtFinal + "'  AND ecomm_alertas.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "ecomm_ativ_exec", query.query = "DELETE ecomm_ativ_exec FROM  ecomm_ativ_exec WHERE ecomm_ativ_exec.`data` between '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND ecomm_ativ_exec.filial_id " + filiais + " ;"));
			listQuery.Add(new Querys(query.tabela = "nota_fiscal", query.query = "delete nota_fiscal from nota_fiscal nf  LEFT JOIN nota_fiscal_item nfi ON (nf.nota_fiscal_id =nfi.nota_fiscal_id AND nf.filial_id = nf.filial_id)  LEFT JOIN produto p ON (nfi.produto_id  = p.Produto_id) where nfi.filial_id " + filiais + "  AND nf.dtcadastro BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "' "));
			listQuery.Add(new Querys(query.tabela = "nota_fiscal_item", query.query = "DELETE nota_fiscal_item FROM nota_fiscal_item nfi LEFT JOIN produto p ON (nfi.produto_id = p.Produto_id) LEFT JOIN nota_fiscal nf ON(nfi.nota_fiscal_id = nf.nota_fiscal_id AND nfi.filial_id =  nf.filial_id) WHERE nfi.filial_id " + filiais + " AND nf.dtcadastro BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "' OR nf.nota_fiscal_id IS NULL AND nfi.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "xml_nfe", query.query = " delete xml_nfe from xml_nfe xf LEFT JOIN nota_fiscal nf ON(xf.nota_fiscal_id = nf.nota_fiscal_id AND xf.filial_id = nf.filial_id) WHERE nf.filial_id " + filiais + " and nf.dtcadastro BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "'  OR nf.nota_fiscal_id IS NULL AND xf.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "paf_req25_r05", query.query = "DELETE paf_req25_r05 FROM  paf_req25_r05 p5 INNER  JOIN paf_req25_r04 p4  ON (p5.paf_req25_r04_id = p4.paf_req25_r04_id ) WHERE p4.filial_id " + filiais + " AND p4.dtcadastro BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "';"));
			listQuery.Add(new Querys(query.tabela = "im_atualizacao", query.query = "DELETE im_atualizacao  from im_atualizacao WHERE im_atualizacao.data_hora BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND im_atualizacao.filial_id  " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "transacao_pbm", query.query = "DELETE transacao_pbm FROM transacao_pbm WHERE transacao_pbm.data_hora BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "' AND transacao_pbm.filial_id " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "estoque_posterior", query.query = "DELETE estoque_posterior FROM estoque_posterior ep  JOIN produto p ON (ep.produto_id =  p.Produto_id)  JOIN filial f ON(ep.filial_id = f.filial_id)   left JOIN movment m ON (ep.movment_id = m.movment_id AND f.filial_id = m.filial_id)  WHERE ep.dtalteracao BETWEEN '" + tab.dtInicial + "' and '" + tab.dtFinal + "'  AND f.filial_id  " + filiais + " OR m.movment_id IS NULL AND f.filial_id  " + filiais + ";"));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));
			listQuery.Add(new Querys(query.tabela = "", query.query = ""));





			return (listQuery).ToString();
			
			
			
			
			
			
		}
	}
}
